### ISSUE TITLE
Build and publish Axon images for M1

### ISSUE THREAD

**Issue by serejke** [axonweb3/axon#1135]
### Propose-a-new-feature

Describe the solution you'd like:

In addition to the `linux/amd64` images published to https://hub.docker.com/r/axonweb3/axon/tags

developers working on M1 chip will be happy if you also build and publish `linux/arm64`

We're running Axon nodes locally for testing and development, and we have to build the images locally with `cargo build`, but it takes significant time (>10m on my machine) and requires patching of `axon-devops`

### Alternatives you've considered

Describe alternatives you've considered:

**Comment by liya2017** [comment]
will suuport M1 binary on next release, but for linux/arm64 docker image have some issue, need sometimes to build and test it.

**Comment by KaoImin** [comment]
Fix in #1147

**Comment by liya2017** [comment]
Also support docker image for linux/arm64
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/32123500/231941203-78528e5a-6db3-46d8-a7ed-94cf105f872b.png">
Tried it and worked fine on my side,  please have a try feel free and let me know if you have any issue.

**Comment by serejke** [comment]
@liya2017 why there is no multi platform (arm64) image for the latest `v0.1.0-beta.1` release?

https://hub.docker.com/r/axonweb3/axon/tags

<img width="578" alt="image" src="https://github.com/axonweb3/axon/assets/6849689/8c956a64-05d5-4c43-813a-febbced09bb5">

**Comment by liya2017** [comment]
> @liya2017 why there is no multi platform (arm64) image for the latest `v0.1.0-beta.1` release?

Hi @serejke, sorry for the inconvenience. 

We noticed that, we build the docker image using github actions runner, but requires more resources than provided when  build  the arm64 image  for the latest `v0.1.0-beta.1` ,it's failed  due to OOM errors.

We're thinking of a different way to do this, will let you know once it done.
