### ISSUE TITLE
Consider implementing EIP-1898 (`blockHash` to `defaultBlock` of `eth_call`)

### ISSUE THREAD

**Issue by serejke** [axonweb3/axon#1155]
### Propose-a-new-feature

Describe the solution you'd like:

This Ethereum EIP https://eips.ethereum.org/EIPS/eip-1898 provides more guarantees to indexers (https://thegraph.com/en/) because they can specify the exact block for which to query blockchain state using `eth_call`.

Currently, The Graph has a workaround for non EIP-1898 compatible chains:
https://github.com/graphprotocol/graph-node/blob/7f67bb8836241c4304d5f8c098e39d2eb3708743/chain/ethereum/src/ethereum_adapter.rs#L432

where it uses block number instead of block hash for requests. But it _might_ lead to inconsistent indexing results, if there is a chain reorg happening while the graph is indexing. Probably The Graph is able to detect reorgs later but I can only guess what is the reliability of this.

It would be great if the `eth_call` and other [defaultBlock](https://ethereum.org/en/developers/docs/apis/json-rpc/#default-block) aware methods would parse the block by `blockHash` and return blockchain state at the time of the specific block.

**Comment by KaoImin** [comment]
The EIP-1898 has been implemented in #1101

**Comment by serejke** [comment]
@KaoImin great, thank you! What release is/will it be included to?

**UPD** I see it's part of [v0.1.0-alpha.9](https://github.com/axonweb3/axon/releases/tag/v0.1.0-alpha.9)
