### ISSUE TITLE
Creating multiaddress for node.toml

### ISSUE THREAD

**Issue by distributedstatemachine** [axonweb3/axon#1158]
### What happened

Describe the problem details:

The current axon kubernetes configurations deploy 4 nodes , which we do not believe would uphold BFT guarantees. In order to alleviate this , we are planning to add an additional node.

While examining the [node.toml](https://github.com/axonweb3/axon/blob/main/devtools/chain/config.toml#L36), I am trying to understand how you precompute this value, as I cannot find any generators similar to the genesis one to create this.

**Comment by serejke** [comment]
@samtvlabs `axon-cli` has `config-gen` subcommand that [fills](https://github.com/axonweb3/axon-cli/blob/7fb73f704e1393257237d899c8bfd0924462029e/src/axon_nodes/config.rs#L412) these values ([doc](https://docs.axonweb3.io/getting-started/for-dapp-devs/zero_to_axon_with_axon_cli#managing-axon-nodes)).

Axon team, your comments are welcome!

**Comment by distributedstatemachine** [comment]
Thanks!
