### ISSUE TITLE
The states of the same genesis block are different for different Axon versions

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1274]
### Current Behavior

The state root of the same genesis block should be the same.

But when run Axon with `v0.1.0-beta.5`, it returns a different state root with `v0.1.0-beta.0`.

### Expected Behavior

I used `git bisect` to create a empty dev chain and checked the state root of its genesis block again and again, and finally I found the state root was changed between commit [5819560 and dd629ee](https://github.com/axonweb3/axon/compare/5819560..dd629ee).

The state root of the dev chain (ref: [devtools/chain](https://github.com/axonweb3/axon/tree/5819560/devtools/chain)) I got through JSON-RPC:

- Before commit 5819560 (included): `0x13d66227ff58a309512520b553454300483111ae4d3cfe7c39af2f12047f8893`
- After commit dd629ee (included): `0x65f57a6a666e656de33ed68957e04b35b3fe1b35a90f6eafb6f283c907dc3d77`

### OS

Not Associated

### Axon version

v0.1.0-beta.x

### Kernel

Not Associated

### Relevant log output

No log output.

### Anything else?

- Was the changed state root is as expected?
- There should be some checks in CI.

**Comment by KaoImin** [comment]
This is caused by #1206 which is a breaking change. So the v0.1.0-beta.2 is not compatible with v0.1.0-beta.1.

**Comment by chaoticlonghair** [comment]
Let me use the [`devtools/chain/genesis_single_node.json`] as demo to show why it's not compatible.

- First, let's focus on what changed in #1206.

  - Before that PR:
  https://github.com/axonweb3/axon/blob/5819560f50e9e80a2c74392a49cc9f784e1af066/protocol/src/types/transaction.rs#L91

  - After that PR:
  https://github.com/axonweb3/axon/blob/dd629ee2ce036507fedcc9914d050b1b498b154e/protocol/src/types/transaction.rs#L91

- And, let's check the first transaction in [`devtools/chain/genesis_single_node.json`]:
  https://github.com/axonweb3/axon/blob/bc7149f37330903e0a1a173f7c86cd22d483bb71/devtools/chain/genesis_single_node.json#L42-L43

  After test, I found that this transaction cost `2422845` gas, then:

  - Before that PR:

    ```
    fee_cost = gas * gas_price = 0
    ```

  - After that PR

    ```
    fee_cost = gas * max_priority_fee_per_gas = 3239343765
    ```
  
- But, since the #1258, the receipt has set to incorrect data.

  In previous example, the data will always be empty.

  So the receipts root will be the same no matter with or without #1206.

  But state root will be different.

[`devtools/chain/genesis_single_node.json`]: https://github.com/axonweb3/axon/blob/bc7149f37330903e0a1a173f7c86cd22d483bb71/devtools/chain/genesis_single_node.json

**Comment by chaoticlonghair** [comment]
@KaoImin Close this issue?
