### ISSUE TITLE
Transactions root of genesis block is incorrect

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1305]
## Current Behavior

When calculating the genesis hash as previous hash of block 1, the transactions root is not set.

I'm not sure whether there is any transactions in genesis block.

But, even there is no transactions, the transactions root still could NOT be zeros, since there is a default value `RLP_NULL`.

https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/core/consensus/src/engine.rs#L73-L79

https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/protocol/src/types/primitive.rs#L33-L36

### Expected Behavior

Transactions root in genesis block should follow the consensus rules.

As a comparison, the receipts root and state root are refreshed before saved.

https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/core/run/src/lib.rs#L168-L172

### OS

Not Associated

### Axon version

v0.1.0-beta.5

### Kernel

Not Associated

### Anything else?

Sadly, if it has a fix, the fix will be a break change.

And, please check all of the following fields again:

https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/devtools/chain/genesis_single_node.json#L4-L29

Which fields should be reset after the genesis block executed?

Select them in the following list:

- [ ] version
- [ ] prev_hash
- [ ] proposer
- [x] state_root
- [x] transactions_root
- [x] signed_txs_hash
- [x] receipts_root
- [x] log_bloom
- [ ] difficulty
- [ ] timestamp
- [ ] number
- [x] gas_used
- [ ] gas_limit
- [ ] extra_data
- [ ] mixed_hash
- [ ] nonce
- [ ] base_fee_per_gas
- [ ] proof
- [ ] call_system_script_count
- [ ] chain_id

**Comment by KaoImin** [comment]
This is a bug, the transactions root in genesis file is empty, however, Axon does not calculate the transactions root when execute genesis block.

**Comment by chaoticlonghair** [comment]
How about other similar fields?

For example, `signed_txs_hash`, `log_bloom`, `gas_used` and so on.

p.s. I updated the description of this issue, please select the fields at there.

**Comment by Flouse** [comment]
- https://github.com/axonweb3/axon/pull/1331#pullrequestreview-1581674167
> @KaoImin : Missing the signed_txs_hash and gas_used fields.

**Comment by KaoImin** [comment]
This issue is fixed in #1302 #1332
