### ISSUE TITLE
Refactor the `config.toml`, split the consensus parameters.

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1307]
### What is "consensus parameters"?

If it changed, the chain state will be changed, then it is a consensus parameter.

### Why I propose this feature?

Same reason as #1275: the executable binary should be halt when it found the consensus parameters are changed, to make sure no inconsistent data are stored.

My solution is:
- Serialize all consensus parameters in a specify order and calculate a hash, store the hash into storage, check it when axon runs.

But the problem is:
- Consensus parameters are not a separated.

In axon's [config.toml](https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/devtools/chain/config.toml):

- `accounts` section are consensus parameters.

  https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/devtools/chain/config.toml#L10-L12

- `consensus` section is consensus parameters.

  https://github.com/axonweb3/axon/blob/8f3eded7d2d3a4e844d45e37faf585a3739d81b0/devtools/chain/config.toml#L65-L66

- But, other parameters are not consensus parameters, for example, `http_listening_address`, `maxconn` and `log_path`.

In future, there will be more consensus parameters, such as `contract_limit`, `hardfork_height`.

So, if those consensus parameters are split, things will be easier.

**Comment by chaoticlonghair** [comment]
### Some Questions

- Does `consensus.sync_txs_chunk_size` affect the consensus?

  From its name, it looks like a parameter that how many transactions can be synchronized one time.

  I'm not sure whether it's able to affect the consensus.

- Besides `accounts` and `consensus.sync_txs_chunk_size`, is there any other parameters can affect the consensus?

  For example, `crosschain_contract_address`, `wckb_contract_address`, `executor.light`.

**Comment by KaoImin** [comment]
> Does `consensus.sync_txs_chunk_size` affect the consensus?

No. It only controls how many transactions that will be pull once to reduce the press of network.

> Besides `accounts` and `consensus.sync_txs_chunk_size`, is there any other parameters can affect the consensus?  
> For example, `crosschain_contract_address`, `wckb_contract_address`, `executor.light`.

These three configs should be removed. They are outdated.
