### ISSUE TITLE
Unable to start Axon with Single Node

### ISSUE THREAD

**Issue by distributedstatemachine** [axonweb3/axon#1324]
## Description

I am unable to start Axon on the main branch .

```shell
ubuntu@ip-172-31-95-221:~/axon$ cargo run -- run -c devtools/chain/config.toml -g devtools/chain/genesis_single_node.json
    Finished dev [unoptimized + debuginfo] target(s) in 0.78s
     Running `target/debug/axon run -c devtools/chain/config.toml -g devtools/chain/genesis_single_node.json`
Error [ProtocolError] Kind: Codec Error: Rlp("RlpExpectedToBeList")
```

### Expected Behavior

Expected Behavior:

Axon starts up

### OS

Ubuntu 22.04

### Axon version

main 680e53ef8b7f7294d424347c32b5245efecafd90

### Kernel

Linux ip-172-31-95-221 5.19.0-1029-aws #30~22.04.1-Ubuntu SMP Thu Jul 13 17:17:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by KaoImin** [comment]
Notice that the #1270 #1302 and #1319 are breaking change, so it is not compatible with the old data. So is there any old data in the environment?

**Comment by Flouse** [comment]
> Notice that the #1270 #1302 and #1319 are breaking change, so it is not compatible with the old data. So is there any old data in the environment?

Hi, @samtvlabs 
Would you try cleaning up  the old chain data in [devtools/chain/data](https://github.com/axonweb3/axon/blob/f29d8b05b327385882930e3862402a076726a739/devtools/chain/config.toml#L5C3-L5C3) and then restart Axon?

**Comment by distributedstatemachine** [comment]
Thanks this resolves this
