### ISSUE TITLE
Use another default devnet chain_id rather than 2022

### ISSUE THREAD

**Issue by Flouse** [axonweb3/axon#1337]
https://chainlist.org/chain/2022 is used.

**Comment by Flouse** [comment]
By the way,
@samtvlabs Are you going to register Khalani testnet (10012) on https://chainid.network/ ?
```bash
curl --location --request POST 'https://testnet.khalani.network/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "eth_chainId",
    "params": []
}'
```

**Comment by chaoticlonghair** [comment]
References:
- Register a chain: https://github.com/ethereum-lists/chains.
- Register a coin for HD wallets: https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by distributedstatemachine** [comment]
Yes we are and thanks for reminding me its in our back log. will get to it shortly.
