### ISSUE TITLE
CI failed since #1371

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1383]
### Current Behavior

I checked 3 continued commits on main branch.
The following 2 CI checks could NOT be passed since #1371 merged.

- E2E Tests: https://github.com/axonweb3/axon/actions/runs/6008524216/job/16296313752
- Web3 Compatible Tests: https://github.com/axonweb3/axon/actions/runs/6008524252/job/16296408914

### Expected Behavior

.

### OS

Not Associated

### Kernel

Not Associated

**Comment by Flouse** [comment]
### Why did the CI checks were not work for the PR?

Maybe the ref of the called workflows should be updated?
https://github.com/axonweb3/axon/blob/6548ea0febcdf00ea01464e4897542fc2fa54be9/.github/workflows/entry_workflow.yml#L95-L96
