### ISSUE TITLE
ci: fix error: unrecognized subcommand 'init'

### ISSUE THREAD

**Issue by Flouse** [axonweb3/axon#1407]
### error: unrecognized subcommand 'init' 
https://github.com/axonweb3/axon/actions/runs/6086568530/job/16529035375#step:5:50

## Related PRs
- https://github.com/axonweb3/axon/pull/1386
- https://github.com/axonweb3/axon/pull/1398
- https://github.com/axonweb3/axon/pull/1403

**Comment by chaoticlonghair** [comment]
> Status: Downloaded newer image for ghcr.io/flouse/axon:dev

[Not the latest Axon docker.](https://github.com/axonweb3/axon/actions/runs/6086568530/job/16529035375#step:5:13)

Maybe you can push a docker and rerun the workflow, to test if the `entrypoint.sh` works.

**Comment by Flouse** [comment]
> Not the latest Axon docker.
