### ISSUE TITLE
The genesis transactions are opaque with poor readability

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1408]
### What happened

At present, the genesis transactions are generated from previous genesis transactions.

https://github.com/axonweb3/axon/blob/283195b357b60b5a023d7d0610396e4842da86ea/devtools/genesis-generator/src/main.rs#L42-L53

- So, what are the first genesis transactions?

  How to generate the first genesis transactions?

- Since the previous genesis transactions are binary data, how to prove they are safety and trusted, and there are no malicious behaviors in them.

Should the genesis transactions be generated from configurations?

**Comment by Flouse** [comment]
> * So, what are the first genesis transactions?
>   How to generate the first genesis transactions?

I think we should try to use genesis-generator to generate the first genesis transaction too.
@KaoImin said it is a bit complicated and needs to be carefully designed.

## TODO
- [x] Add a document to explain how to use genesis-generator
 https://github.com/axonweb3/axon/blob/fac504c3f28f9ef10dd304bf0d6ee03e86cad9b5/core/run/src/components/chain_spec.rs#L21-L52
- [x] In the test workflows, generate the genesis transactions from readable configurations and double check them against the `genesis_xxx.json` file
  > In this way, the genesis-generator will be well tested too.
  => https://github.com/axonweb3/axon/pull/1450
