### ISSUE TITLE
refactor the extra_data struct to accommodate future possibilities

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1437]
## Foreword

Not about features, just about implementation details.
I don't want to block those PRs, so I write a standalone issue.
We can do them later if they are confirmed after discussion.

:warning: No proposals are final conclusion, I didn't think too much. New proposals are welcome.

### The Configurations

At first, I approved the following code.

- https://github.com/axonweb3/axon/blob/e719adb9705794393246583469fc305ed2ec8097/devtools/chain/specs/single_node/chain-spec.toml#L13-L15

Finally, I realized that:

- First, common developers could not understand that `block_number` is related to `hardfork` features.

  It's not a good naming.

- Second, `extra_data` should has a general usage, not just used as hardfork features.

My Proposal is reduce the coupling:

- Use a standalone `[hardfork]` section to represent the hardfork features.

We can save the data into `extra_data` or not, but we don't have to reflect the internal implementation details at interface levels.

### The Serialization

As I said above, the `extra_data` should be be used for a general purpose; if we want to add new data into header in future, we also can put them into `extra_data`.

So, so current serialization is not reasonable.

https://github.com/axonweb3/axon/blob/e719adb9705794393246583469fc305ed2ec8097/common/config-parser/src/types/spec.rs#L43
https://github.com/axonweb3/axon/blob/e719adb9705794393246583469fc305ed2ec8097/common/config-parser/src/types/spec.rs#L264-L266

If we put some other data into `extra_data` in future, how to distinguish them?
If the new data could exists with hardfork data, how to do that? A new serialization?

I have few simple proposals:

- Add a new field into block header for hardfork features.

- Let the bytes of `extra_data` to represent a `Option<Vec<bytes>>`.

  - The first bytes used for hardfork features.

  - The second bytes could be user-provided data, the block miners can record their personal data.

  - Other bytes are consensus reserved. 
  
    They should not exists at present, we should check the length of `extra_data <= 2`.

  So, if we want to expand `extra_data` filed in future, the compatibility is not broken.

- Same as the above proposal but add a bits map to avoid empty vector items.

  For example, if a new feature have to add a new data into `extra_data`, it will be record in `extra_data[2]` with above design, then we have to add an empty bytes to `extra_data[1]` even the hardfork features is empty now.

  If we let the `extra_data[0]` to be a bits map to explain which data is saved in current `extra_data`, we can avoid those empty bytes.

**Comment by chaoticlonghair** [comment]
@driftluo @KaoImin @Flouse

**Comment by Flouse** [comment]
It's nice to hear this suggestion.

The reason that "Axon may put some other data into `extra_data` in the future" **is strong**.

In short, I support @yangby-cryptape 's proposal:
### refactor the `extra_data` struct to accommodate future possibilities.

Would like to hear your opinions.
@driftluo @KaoImin

**Comment by Flouse** [comment]
https://github.com/axonweb3/axon/blob/e719adb9705794393246583469fc305ed2ec8097/devtools/chain/specs/single_node/chain-spec.toml#L14
- [x] meeting note: If this config (block_number in genesis config) is useless, try to remove it
