### ISSUE TITLE
[MetaMask] Failed to add network following the official docs.

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1456]
### What happened

I tried sending a transaction following the steps in the official docs ["Send Transactions On Axon Via MetaMask"](https://docs.axonweb3.io/getting-started/for-dapp-devs/send_transactions_on_axon_via_metaMask/).

But I got the following error when I tried to add the Axon network.

> Could not fetch chain ID. Is your RPC URL correct?

I saw an error of a `POST` request in the debugger of my browser.

I have test the RPC URL that I added and it worked well in terminal.

I'm not an expert on MetaMask.
I guess that the RPC for querying chain ID was not existed.

**Comment by Flouse** [comment]
### I can reproduce this network issue:
<img width="1004" alt="image" src="https://github.com/axonweb3/axon/assets/1297478/082f27bd-62e0-489f-b588-cb8f17c44793">

**Comment by Flouse** [comment]
I think the Axon node or https://github.com/axonweb3/axon-proxy may need to support CORS configuration, similar to
> --http.corsdomain Comma separated list of domains from which to accept cross origin requests (browser enforced)
> https://github.com/ethereum/go-ethereum/tree/master#configuration

## References
- https://ethereum.stackexchange.com/a/77032
- https://geth.ethereum.org/docs/developers/dapp-developer/dev-mode#start-geth-in-dev-mode

**Comment by chaoticlonghair** [comment]
> I think the Axon node or https://github.com/axonweb3/axon-proxy may need to support CORS configuration, ...

I haven't noticed the project Axon-proxy before.

I created an issue for it, axonweb3/axon-proxy#8, which is related to this issue.

p.s. I noticed that there is an internal axon JSON-RPC server behind cloudflare.

**Comment by Flouse** [comment]
- [x] @sunchengzhu Please help verify the doc https://docs.axonweb3.io/getting-started/for-dapp-devs/send_transactions_on_axon_via_metaMask/ again

**Comment by wenyuanhust** [comment]
> * [x]  @sunchengzhu Please help verify the doc https://docs.axonweb3.io/getting-started/for-dapp-devs/send_transactions_on_axon_via_metaMask/ again

The doc is verified before. If it did not work afterwards, it should be caused by later axon updates. To make the docs always work, we'd better add docs related tests. Have we done this?

**Comment by blckngm** [comment]
Axon-proxy already supports CORS:

https://github.com/axonweb3/axon-proxy/blob/ef90d777ed1ad16340261c190a7f4c83cd8bddc0/src/server.rs#L35-L37

**Comment by Flouse** [comment]
> Axon-proxy already supports CORS:
> 
> https://github.com/axonweb3/axon-proxy/blob/ef90d777ed1ad16340261c190a7f4c83cd8bddc0/src/server.rs#L35-L37

cc @Simon-Tl
