### ISSUE TITLE
Call the built-in `Metadata` contract causes an error.

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1457]
### Summary

Call the built-in `Metadata` contract causes an error:

> CKB-VM error execution reverted

### How to reproduce?

- Create a interface file for `Metadata` contract.

  - Base on [the built-in `Metadata` contract SOL file].

  - Base on [the internal `Metadata` contract ABI file].

- Call the method `getMetadata(uint64 epoch)` from another contract.

  ```solidity
  function getMetadata(uint64 epoch) public view returns (IMetadataManager.Metadata memory){ 
    address addr = 0xFFfffFFfFFfffFfFffFFfFfFfFffFfffFFFFFf01;
    return IMetadataManager(addr).getMetadata(epoch);
  }
  ```

  References:

  - Method signature in [the built-in `Metadata` contract SOL file].

    https://github.com/axonweb3/axon/blob/71f5bad3ae581108b708e671c3e3573af4564dde/builtin-contract/metadata/contracts/metadata.sol#L139

  - Method signature in [the internal `Metadata` contract ABI file].

    https://github.com/axonweb3/axon/blob/71f5bad3ae581108b708e671c3e3573af4564dde/core/executor/src/system_contract/metadata/abi/metadata_abi.json#L141-L148

There are several issues:

- [x] Why the error message contains "CKB-VM"?

  I didn't call any contract which uses CKB-VM.

- [x] How to call `Metadata` contract in Solidity scripts with the provided method?

  The provided method is:

  https://github.com/axonweb3/axon/blob/71f5bad3ae581108b708e671c3e3573af4564dde/core/executor/src/precompiles/metadata.rs#L11-L17

  p.s. Axon should NOT force users to write assembly.

- [x] Should there be some tests before new changes on the built-in `Metadata` contract? (ref: #1454)

  Did I miss some things?
  I didn't find any tests under [the `test` directory](https://github.com/axonweb3/axon/tree/71f5bad3ae581108b708e671c3e3573af4564dde/tests) for the built-in `Metadata` contract.

  I'm neither an expert on JavaScript nor an expert on Solidity.
  Also, I haven't understood the storage model of Axon completely, yet.

  I hope someone can add such tests (or examples) to increase confidence for the changes of the built-in `Metadata` contract.

[the built-in `Metadata` contract SOL file]: https://github.com/axonweb3/axon/blob/71f5bad3ae581108b708e671c3e3573af4564dde/builtin-contract/metadata/contracts/metadata.sol
[the internal `Metadata` contract ABI file]: https://github.com/axonweb3/axon/blob/71f5bad3ae581108b708e671c3e3573af4564dde/core/executor/src/system_contract/metadata/abi/metadata_abi.json

- [x] Provide an interface SOL file for the built-in `Metadata` contract, and use unit tests to make sure it will be updated when the contract is changed.

  Axon should NOT let users to write the interface manually.

  It's better than provide a contract SOL file without code for implementation. (ref: #1449)

### Expected Behavior

.

**Comment by chaoticlonghair** [comment]
In the issue body, I told one of my opinion:

> Provide an interface SOL file for the built-in Metadata contract, and use unit tests to make sure it will be updated when the contract is changed.

Now I withdraw my previous opinion.

We could NOT provide any interface of the Metadata contract.

One of those reasons is: If the interface is valid, then all `Metadata` items in `mapping(uint64 => Metadata) metadata_set;` should have the same structure at any block.

https://github.com/axonweb3/axon/blob/6fe5777e0b4a9b994dc84a56a00005745fd05085/builtin-contract/metadata/contracts/metadata.sol#L57-L58

That means this mapping should be refreshed after any hardfork and fill all new-added fields to all previous items.

**Comment by chaoticlonghair** [comment]
The all data stored for this contract are incompatible with EVM state storage.

Here I just give one example:

https://github.com/axonweb3/axon/blob/6fe5777e0b4a9b994dc84a56a00005745fd05085/core/executor/src/system_contract/metadata/store.rs#L93-L96

The key for the following mapping should be `keccak256(concat(epoch_bytes, mapping_slot_in_bytes))`.

https://github.com/axonweb3/axon/blob/6fe5777e0b4a9b994dc84a56a00005745fd05085/builtin-contract/metadata/contracts/metadata.sol#L57-L58

The slot here should be `0` or `1`; I'm not sure now, since the type of 1st internal value in struct definition is `constant`.

https://github.com/axonweb3/axon/blob/6fe5777e0b4a9b994dc84a56a00005745fd05085/builtin-contract/metadata/contracts/metadata.sol#L8

I guess a `constant` may not cost a slot, but I haven't find any docs about it yet.

### Summary

This also is a reason for "why we could NOT provide any interface of the Metadata contract".

- If we want to create an EVM-compatible contract, obviously the `Metadata` contract is NOT.

- If the `Metadata` contract can be EVM-incompatible, then a design document is required.

  To prove all data stored are in control (as design), not just a random implementation picked by the PR authors. 

### References

- [How are mappings stored in smart contract storage?](https://docs.alchemy.com/docs/smart-contract-storage-layout#how-are-mappings-stored-in-smart-contract-storage)

**Comment by KaoImin** [comment]
The system contracts do not allow other sol contracts to be called directly, because they are all `write` functions. If you want to `read` the data contains by system contracts, Axon provides some `precompile` to do this.

**Comment by chaoticlonghair** [comment]
- So, why you put a SOL file in directory without any documents?

  And in a latest PR, you will update that SOL file.

  As a user, you want to me how to understand that?

- I didn't `read` data directly, I called the function which provided by axon developers in that SOL file.

  Was axon developers provided that method in that SOL file?

  Can't users use that method?

  So, any usages of that SOL file, except confuse users?

  - That method in the current revision.

    https://github.com/axonweb3/axon/blob/6fe5777e0b4a9b994dc84a56a00005745fd05085/builtin-contract/metadata/contracts/metadata.sol#L138-L139

  - That method in the next revision, which is in axonweb3/axon#1449 now.

    https://github.com/axonweb3/axon/blob/7e8eb1643c9979529cd1d38b7c6a58eefb216ff3/builtin-contract/metadata/contracts/metadata.sol#L71

**Comment by Flouse** [comment]
### After #1449 
The latest interfaces of Metadata contract is
  https://github.com/axonweb3/axon/blob/4c43ed4c02757661ab0862341697665be33f20f7/builtin-contract/system-contract/contracts/metadata/Metadata.sol#L54-L67

- The getMetadata function was removed, instead by [axon_getMetadataByNumber](https://github.com/axonweb3/axon/blob/f000c0f2651dc6a123e4d7d84f9262cb292f3ef1/core/api/src/jsonrpc/mod.rs#L215) RPC,
  because the `returns (IMetadataManager.Metadata)` may be changed if a hardfork happened.

**Comment by Flouse** [comment]
> * Why the error message contains "CKB-VM"?
>   I didn't call any contract which uses CKB-VM.

fixed by https://github.com/axonweb3/axon/pull/1484/files#diff-7dedadc749f34a439efcf21029dbc46d5551c34bafd11e30faf0f6d3ee688650R57-R137
