### ISSUE TITLE
A strange v0 tag

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1478]
### What happened

- Anyone can see this strange release.

- It already exists few weeks ago.

  First time I saw it was 2023-07-10, it refers to a commit between `v0.1.0-beta.4` and `v0.1.0-beta.5`.

  I had reported this issue in your discord channel.

- Keep an incorrect tag to avoid conflicts is acceptable, but this tag was force-pushed yesterday.

  :bell: Changes of tags cause conflicts for developers, it isn't allowed by mostly open-source projects.

<details><summary>A screenshot.</summary>

![image](https://github.com/axonweb3/axon/assets/30993023/2d674d3c-a12c-48ed-ae81-b14183f61493)

</details>

**Comment by Flouse** [comment]
> ### Contact Details
> _No response_
> 
> ### What happened
> * Anyone can see this strange release.
> * It already exists few weeks ago.
>   First time I saw it was 2023-07-10, it refers to a commit between `v0.1.0-beta.4` and `v0.1.0-beta.5`.
>   I had reported this issue in your discord channel.
> * Keep an incorrect tag to avoid conflicts is acceptable, but this tag was force-pushed yesterday.
>   🔔 Changes of tags cause conflicts for developers, it isn't allowed by mostly open-source projects.
> 
> A screenshot.
> ![image](https://user-images.githubusercontent.com/30993023/274844805-2d674d3c-a12c-48ed-ae81-b14183f61493.png)

Maybe the v0 tag was designed to track the latest version of v0.
But I think it is better to use a `v0.x` **branch** instead of a tag.

What is your suggestion?

**Comment by chaoticlonghair** [comment]
> Maybe the v0 tag was designed to track the latest version of v0.
> But I think it is better to use a `v0.x` **branch** instead of a tag.
> 
> What is your suggestion?

I don't have any personal suggestion.

"Do NOT change a tag on a remote repository, unless sensitive data was leaked."
It's just commonly accepted convention in the open-source world.

References:
- Search "git tag bad practice" or "git replace tag remote" with any search engine.
- Execute `git help tag` and see the "DISCUSSION" section.

p.s. I only do that on repositories which I refuse community cooperation.

**Comment by Flouse** [comment]
I think I found the reason of `v0` tag:
https://github.com/axonweb3/axon/actions/runs/6588649493/job/17945789520#step:3:2

I am going to remove the `force-push` job.
cc @KaoImin @yangby-cryptape
