### ISSUE TITLE
In design, are system contracts addresses able to be payable?

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1490]
### Question

In other words, could I send tokens to a system contract address?

**Comment by KaoImin** [comment]
~~Currently, you can do this. However, it is a waste of tokens.~~

**Comment by chaoticlonghair** [comment]
> Currently, you can do this. However, it is a waste of tokens.

But when I do transfer in MetaMask, it returns "Invalid system script transaction".

So, can you confirm what you said above?

**Comment by KaoImin** [comment]
> > Currently, you can do this. However, it is a waste of tokens.
> 
> But when I do transfer in MetaMask, it returns "Invalid system script transaction".
> 
> So, can you confirm what you said above?

Sorry, I forget the call system contract inspection:
https://github.com/axonweb3/axon/blob/e64f03c7d2009778d5a4a519b57e564ce8fa272d/core/mempool/src/adapter/mod.rs#L182-L200
Nobody can send tokens to a system contract address because if the transaction calls a system contract address, executor will not execute it in EVM.
https://github.com/axonweb3/axon/blob/e64f03c7d2009778d5a4a519b57e564ce8fa272d/core/executor/src/system_contract/mod.rs#L204-L223

**Comment by chaoticlonghair** [comment]
> Nobody can send tokens to a system contract address ...

Please check the Metadata contract address in the Axon internal testnet.

Its balance is 1,539.471495196523525479 ETH.

> I forget the call system contract inspection ...

The inspection could be bypassed.

---

#### How to reproduce?

- [`send`](https://docs.soliditylang.org/en/v0.8.21/types.html#address)

---

I have checked the latest commit [8a0e1a9](https://github.com/axonweb3/axon/tree/8a0e1a9745b1d857c200e1f926b0d5d8f3f82479). I think I have got the same result.

**Comment by KaoImin** [comment]
@driftluo  please check why the transfer process of system contract transactions can be executed. The system contract does not execute in EVM and change the balance.

**Comment by chaoticlonghair** [comment]
> @driftluo please check why the transfer process of system contract transactions can be executed. The system contract does not execute in EVM and change the balance.

Because the rust code won't be called in the EVM executor.

The executor will fetch the data of that address and execute the data as code.
