### ISSUE TITLE
Different JSON-RPC methods return different `block_hash` for a same height.

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1506]
### Summary

In `Proof`, `Vote` and some other structs, how does users know the field named as `block_hash` but filled with `proposal_hash`?

### An Example

- Get proof via `axon_getProofById`.
- Get block via `eth_getBlockByNumber`.
- Users will find that they have different `block_hash` for same height.

**Comment by KaoImin** [comment]
It is better to rename `block_hash` field in `Proof` and `Vote` struct with `proposal_hash`.
