### ISSUE TITLE
For a same verifier (based on its BLS private key), the `address` in metadata and consensus could be different.

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1511]
### Description

- When initialize the chain data, `metadata.verifier_list` are loaded from the `chain-spec.toml`.

  <details><summary>Click for details.</summary><br/>

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/common/config-parser/src/types/spec.rs#L32

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/protocol/src/types/primitive.rs#L301

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/protocol/src/types/primitive.rs#L461-L469

  </details>

- And it is written into storage directly.

  <details><summary>Click for details.</summary><br/>

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/core/run/src/lib.rs#L435

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/core/run/src/lib.rs#L444-L450

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/core/run/src/lib.rs#L493

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/core/executor/src/system_contract/mod.rs#L123

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/core/executor/src/system_contract/mod.rs#L180-L181

  </details>

- But when initialize the crypto data for consensus, the `pub_key` is replaced and `address` is abandoned.

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/core/run/src/lib.rs#L363-L372

  _:thinking: The following steps make me confused deeply._

  - Generate new `address` from original `pub_key`.
  - Generate new `pub_key` from original `bls_pub_key`.
  - Original `address` is abandoned.

  So, why users have to provide the `addresses`?

  _p.s.: I checked, the logic is same as the logic before refactor axon commands line. (ref: [previous version](https://github.com/axonweb3/axon/blob/de44cf52c0b7daebc3d6a45375c715f0bf9a26b7/core/run/src/lib.rs#L532-L539))._

- Back to the metadata contract, it uses the original `address` which is stored in storage.

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/core/executor/src/system_contract/metadata/mod.rs#L63-L69

  https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/core/executor/src/system_contract/metadata/handle.rs#L44-L47

### Question

- What does it mean? Is is a bug?

- If there is an address stored in metadata, but it could not be derived from its corresponding public key, what would happen?

**Comment by KaoImin** [comment]
https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/core/run/src/lib.rs#L363-L372
The crux of this question is these code. As you can see, the `bls_pub_keys` variable is an argument of `OverlordCrypto`, and it is only used in `OverlordCrypto`.
https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/core/consensus/src/util.rs#L34-L47
`OverlordCrypto` is employed for signing and verifying consensus message signatures. Due to Axon's utilization of aggregated signatures, some messages don't require broadcasting; an unicast to a peer suffices. To facilitate this, the consensus module must include the peer's P2P address. The peer's public key is stored in the network instead of an address, thus a secp256k1 public key serves as the address in this context.

**Comment by chaoticlonghair** [comment]
Thanks for your comment.

Let's just simplify things.

https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/devtools/chain/specs/single_node/chain-spec.toml#L79-L82
https://github.com/axonweb3/axon/blob/363b49fcb3162e5ed2255e89fea0019b9e0c68f3/devtools/chain/config.toml#L5-L6

As you said above, is the following description right?
```
- net_privkey_file -> params.verifier_list.address         # thus a secp256k1 public key serves as the address in this context.
- bls_privkey_file -> params.verifier_list.bls_pub_key
- What's `params.verifier_list.pub_key`?
```

Please copy and modify the above content, you can just use lines to point the relation, instead of complex description.

**Comment by chaoticlonghair** [comment]
As I know, each node have at most 2 private keys: one is secp256k1 key and one is bls key.

- If I'm right, but each verifier has be configured 3 things -- `bls_pub_key`, `pub_key` and `address` -- so which 2 of them are related? And, are these 2 related things checked, before writing into metadata?

- If I'm wrong, which is the 3rd private key?
