### ISSUE TITLE
Send raw transaction successfully but failed to get it by its hash through web JSON-RPC apis.

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1523]
### Description

When developers develops a Dapp, after sending a transaction, they may want to get the status of that transaction.

But it will be failed.

#### Why it doesn't occur in CI tests?

- The abnormal results are ignored. CI doesn't check them.

  ```javascript
  for (let i = 0; i < count; i++) {
      response = await provider.getTransactionReceipt(txHash);
      if (response == null) {
          await sleep(2000)
          continue;
      }
  ```

  Ref: [`getTxReceipt(..)` in axonweb3/axon-test](https://github.com/axonweb3/axon-test/blob/0e2e379ac17175c301115127ea679f1d0085ddc3/test/utils/rpc.js#L125-L139)

- [Hardhat] is a JavaScript toolchain, it is very slow.

  - I tried the simplest example with [Hardhat] and Axon, it's almost failed 5%.
  
  - I tried the simplest example with [Foundry] and Axon, it's almost failed 99.9%.

  - I tried the simplest example with [Foundry] and [Geth], it's 100% success.

  Due to this issue, use [Foundry] to test Axon is impossible at present.

  [Foundry] allows pending status and it will retry for pending transactions but it doesn't allow null status, it will return the error "Transaction dropped from the mempool".

  I don't mean developers have to use [Foundry], but it means some high performance tools will not support Axon.

[Hardhat]: https://hardhat.org/
[Foundry]: https://getfoundry.sh/
[Geth]: https://geth.ethereum.org/

### Reason

- After call `eth_sendRawTransaction`, the RPC will return a response after inserting that transaction into mempool.

  https://github.com/axonweb3/axon/blob/ad4375b415d28b4286ac51874102ac74c99c8cb2/core/api/src/jsonrpc/impl/web3.rs#L313-L318
  https://github.com/axonweb3/axon/blob/ad4375b415d28b4286ac51874102ac74c99c8cb2/core/api/src/adapter.rs#L70-L76
  
  <details><summary>Click here for more details.</summary><br/>
  
  https://github.com/axonweb3/axon/blob/ad4375b415d28b4286ac51874102ac74c99c8cb2/core/mempool/src/lib.rs#L198
  https://github.com/axonweb3/axon/blob/ad4375b415d28b4286ac51874102ac74c99c8cb2/core/mempool/src/lib.rs#L118-L122
  https://github.com/axonweb3/axon/blob/ad4375b415d28b4286ac51874102ac74c99c8cb2/core/mempool/src/pool.rs#L135
  
  </details>

- But when call `eth_getTransactionByHash`, `eth_getTransactionReceipt` or some other APIs, the RPC will read the status from storage directly.

  https://github.com/axonweb3/axon/blob/ad4375b415d28b4286ac51874102ac74c99c8cb2/core/api/src/jsonrpc/impl/web3.rs#L323-L327
  https://github.com/axonweb3/axon/blob/ad4375b415d28b4286ac51874102ac74c99c8cb2/core/api/src/adapter.rs#L139-L145

- (I tested!) 3~5 seconds after sending the transaction successfully, there will still be a chance that the transaction is still in the mempool and hasn't been inserted into storage.

### Proposal Solution

- Shouldn't return the transaction state from storage directly, check the mempool at first.
- Better tests.

**Comment by driftluo** [comment]
The transactions in the axon transaction pool are not executed, that is, there is no Receipt, so it cannot support querying the Receipt of transactions in the transaction pool.

**Comment by chaoticlonghair** [comment]
I tried to fix that, but CI failed and I haven't known the reason yet.

> there is no Receipt,

It's fine, but `eth_getTransactionByHash` should work.

**Comment by Flouse** [comment]
> * The abnormal results are ignored. CI doesn't check them.
>   ```js
>   for (let i = 0; i < count; i++) {
>       response = await provider.getTransactionReceipt(txHash);
>       if (response == null) {
>           await sleep(2000)
>           continue;
>       }
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   Ref: [`getTxReceipt(..)` in axonweb3/axon-test](https://github.com/axonweb3/axon-test/blob/0e2e379ac17175c301115127ea679f1d0085ddc3/test/utils/rpc.js#L125-L139)

@sunchengzhu could you refactor [the test](https://github.com/axonweb3/axon-test/blob/0e2e379ac17175c301115127ea679f1d0085ddc3/test/utils/rpc.js#L125-L139)?

**Comment by chaoticlonghair** [comment]
> could you refactor [the test](https://github.com/axonweb3/axon-test/blob/0e2e379ac17175c301115127ea679f1d0085ddc3/test/utils/rpc.js#L125-L139)?

### My Idea

1.  Call `eth_getTransactionByHash` at first:

    1. If response is error, then throw it.

    1. If response is null, then throw an error, for example: "The transaction was not found".

    1. If response is transaction but its block number is null, then call `eth_getTransactionByHash` again.

    1. If response is transaction and its block number is not null, then go to next step.

3.  Then, call `eth_getTransactionReceiptByHash`:

    The response should not be null.

**Comment by Flouse** [comment]
> but CI failed and I haven't known the reason yet.

![image](https://github.com/axonweb3/axon/assets/1297478/473bf35c-f45e-4138-bd44-d8eebbea35f2)
Maybe we should check the previous commits again.

**Comment by chaoticlonghair** [comment]
At present, the CI checks are failed.

- [Web3 Compatible Test / Run "axon-test"](https://github.com/axonweb3/axon/actions/runs/6767961081/job/18391486421#step:13:26380)
- [v3 Core Tests / Run test 1](https://github.com/axonweb3/axon/actions/runs/6767961074/job/18391486437#step:16:131)
- [v3 Core Tests / Run test 2](https://github.com/axonweb3/axon/actions/runs/6767961074/job/18391486437#step:17:263)

The tests should be fixed before the bugfix (ref: #1526) merged.

**Comment by sunchengzhu** [comment]
> > * The abnormal results are ignored. CI doesn't check them.
> >   ```js
> >   for (let i = 0; i < count; i++) {
> >       response = await provider.getTransactionReceipt(txHash);
> >       if (response == null) {
> >           await sleep(2000)
> >           continue;
> >       }
> >   ```
> >   
> >   
> >       
> >         
> >       
> >   
> >         
> >       
> >   
> >       
> >     
> >   Ref: [`getTxReceipt(..)` in axonweb3/axon-test](https://github.com/axonweb3/axon-test/blob/0e2e379ac17175c301115127ea679f1d0085ddc3/test/utils/rpc.js#L125-L139)
> 
> @sunchengzhu could you refactor [the test](https://github.com/axonweb3/axon-test/blob/0e2e379ac17175c301115127ea679f1d0085ddc3/test/utils/rpc.js#L125-L139)?

The `getTxReceipt` function is commonly used in cases where the transaction object is directly constructed and sent. On the other hand, when sending transactions using contract object methods within Hardhat, such as `contract.waitForDeployment()`, the `getTxReceipt` is not required. The process is handled automatically: it starts with a single call to `eth_getTransactionByHash`, followed by repeated calls to `eth_getTransactionReceipt` until the transaction receipt is successfully obtained (the related requests and responses can be reviewed in the [deploy.log](https://docs-1304641378.cos.ap-shanghai.myqcloud.com/hardhat-rpc/deploy.log)). 

I am planning to revise the `getTxReceipt` function to make its logic consistent with the `eth_getTransactionByHash` and `eth_getTransactionReceipt` invocation patterns found in the contract object methods.

**Comment by chaoticlonghair** [comment]
Blocked by #1529.
