### ISSUE TITLE
Memory capacity exceeded in JSON-RPC server components when run web3 compatible test.

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1534]
### Description

My laptop is old, but it has high performance and **a great quantity of RAM**.

And I started a local Axon node use [the default configuration](https://github.com/axonweb3/axon/tree/37cddb78120608ccb35842d411107b2bdc6f4bb4/devtools/chain).

Then I ran the following command to run the web3 compatible test.
https://github.com/axonweb3/axon/blob/37cddb78120608ccb35842d411107b2bdc6f4bb4/.github/workflows/web3_compatible.yml#L135

After a while, I got:

> [2023-11-08T23:03:38.977904689+08:00 ERROR jsonrpsee_core::server::helpers] Error serializing response: Error("Memory capacity exceeded", line: 0, column: 0) 

Then the test is hung.

I had to press `Ctrl+C` to exit.

### Related CI Checks

Maybe this issue is the reason why many CI checks are failed after few hours tonight:
- [axonweb3/axon Web3 Compatible Tests #2818](https://github.com/axonweb3/axon/actions/runs/6787315348/job/18449847367)
- [axonweb3/axon Web3 Compatible Tests #2820](https://github.com/axonweb3/axon/actions/runs/6793756097/job/18469108138)
- [axonweb3/axon Web3 Compatible Tests #2823](https://github.com/axonweb3/axon/actions/runs/6795148421/job/18472714867)
- [axonweb3/axon Web3 Compatible Tests #2824 Attempt #1](https://github.com/axonweb3/axon/actions/runs/6795300595/job/18473154731)
- [axonweb3/axon Web3 Compatible Tests #2824 Attempt #2](https://github.com/axonweb3/axon/actions/runs/6795300595/job/18483304453)
- [axonweb3/axon Web3 Compatible Tests #2827](https://github.com/axonweb3/axon/actions/runs/6798542990/job/18482899409)
- [axonweb3/axon-test Test with Axon #7](https://github.com/axonweb3/axon-test/actions/runs/6798772921/job/18483587285)

But, if luck enough, the web3 compatible test could be finished in 30 minutes:
- [axonweb3/axon Web3 Compatible Tests #2819](https://github.com/axonweb3/axon/actions/runs/6792450127/job/18465748281)
- [axonweb3/axon Web3 Compatible Tests #2821](https://github.com/axonweb3/axon/actions/runs/6794283345/job/18470432650)
- [axonweb3/axon Web3 Compatible Tests #2822 Attempt #1](https://github.com/axonweb3/axon/actions/runs/6794716156/job/18471564696)
- [axonweb3/axon Web3 Compatible Tests #2822 Attempt #2](https://github.com/axonweb3/axon/actions/runs/6794716156/job/18485422946)
- [axonweb3/axon Web3 Compatible Tests #2828](https://github.com/axonweb3/axon/actions/runs/6799544420/job/18486077591)

### My Guess

- This immediate cause for this issue is [these axon-tests changes](https://github.com/axonweb3/axon-test/compare/0e2e379ac17175c301115127ea679f1d0085ddc3...32824b4f933cb6d4b4612d02f894b6e8dbd0fdd4).

  Reason: All issues was happened after those commits merged.

  It doesn't mean these commits are incorrect.

- I think the underlying cause is some unknown bugs in Axon.

  Reason: The Axon testnet has same errors but its code is old.

- And, axonweb3/axon#1526 reduces the chance of bugs happened to almost 0%.

  Reason: All CI checks could be finished in 30 minutes in this PR.

**Comment by blckngm** [comment]
Error is probably logged here:

https://github.com/paritytech/jsonrpsee/blob/724e23841df5783255cd5b55c1f15308d75a362a/core/src/server/helpers.rs#L276

There is a limit on max response size in jsonrpsee.

**Comment by chaoticlonghair** [comment]
References:
- [The error construction](https://github.com/paritytech/jsonrpsee/blob/724e23841df5783255cd5b55c1f15308d75a362a/core/src/server/helpers.rs#L77)
- [Official solution for the error](https://github.com/paritytech/jsonrpsee/issues/672#issuecomment-1293416621)

---

I still have two question:
- Why it happened after [those axon-tests changes](https://github.com/axonweb3/axon-test/compare/0e2e379ac17175c301115127ea679f1d0085ddc3...32824b4f933cb6d4b4612d02f894b6e8dbd0fdd4) more than before.
- Why #1526 could reduce the chance of bugs happened to almost 0%.

**Comment by chaoticlonghair** [comment]
### References

- #1526
- #1544
- #1548
