### ISSUE TITLE
Should we apply the same logic to all reserved system contracts addresses?

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1590]
### Description

- As the following code defined:

  https://github.com/axonweb3/axon/blob/6a574cdbe0b0f826968602d253721606f2cd5ded/core/executor/src/system_contract/mod.rs#L42-L47

  All addresses between `0xffff..ff00` and `0xffff..ffff` are system contracts.

- But only 3 addresses in them are used.

  https://github.com/axonweb3/axon/blob/6a574cdbe0b0f826968602d253721606f2cd5ded/core/executor/src/system_contract/metadata/mod.rs#L29
  https://github.com/axonweb3/axon/blob/6a574cdbe0b0f826968602d253721606f2cd5ded/core/executor/src/system_contract/ckb_light_client/mod.rs#L20
  https://github.com/axonweb3/axon/blob/6a574cdbe0b0f826968602d253721606f2cd5ded/core/executor/src/system_contract/image_cell/mod.rs#L20

- When executing a system contract, only above 3 contracts that have been clearly defined are dispatched to the system contracts process.
  
  https://github.com/axonweb3/axon/blob/6a574cdbe0b0f826968602d253721606f2cd5ded/core/executor/src/lib.rs#L152-L153
  https://github.com/axonweb3/axon/blob/6a574cdbe0b0f826968602d253721606f2cd5ded/core/executor/src/system_contract/mod.rs#L204-L223

  Other executions which are to the reserved addresses of system contracts are processed as normal executions.

- As far as we know, a normal contract and a system contract are very different.

  - They have different restrictions, for example: #1490.
  - System contracts use special storage, which are isolated.
    - They use different JSON-RPC APIs for storage data and proofs (ref: #1561).

---

:question: So, my question is: once a reserved system contract is enabled in the future, how to treat the difference between now and then after that?

An example of current Axon:
- Now, `0xffff..ff04` is an undeployed system contract address.
  - It's payable.
  - The data, even be empty, should be accessed with `eth_getStorageAt` and the proofs of its storage should be generated with `eth_getProof`.
- Once it is deployed.
  - It's NOT payable.
  - The data should be accessed with `axon_getSystemContractStorageAt` and the proofs of its storage should be generated with `axon_getSystemContractProof`.[^1]

Should we apply the same logic to those reserved system contracts now?

Let all system contracts, even reserved system contracts:
- Should NOT be payable.
- The data should be accessed with `axon_getSystemContractStorageAt` and the proofs of its storage should be generated with `axon_getSystemContractProof`.

[^1]: https://github.com/axonweb3/axon/issues/1561#issuecomment-1814445346

**Comment by Flouse** [comment]
## My Humble Opinion
1. reserved `system_contract_address`es is defined in 
   
 
 
 
 
 https://github.com/axonweb3/axon/blob/6a574cdbe0b0f826968602d253721606f2cd5ded/core/executor/src/system_contract/mod.rs#L42-L47

2. Just return error in `eth_getStorageAt` and `eth_getProof` when an address is `system_contract_address`

3. fix [system_contract_dispatch function](https://github.com/axonweb3/axon/blob/6a574cdbe0b0f826968602d253721606f2cd5ded/core/executor/src/system_contract/mod.rs#L204-L223)
  It should handle all reserved `system_contract_address`es.

## Need confirmations before coding
- [x] @KaoImin 
- [x] @driftluo 
- [x] @yangby-cryptape

**Comment by Flouse** [comment]
> * Just **return error in `eth_getStorageAt` and `eth_getProof` when an address is `system_contract_address`**
> *

I think this change is not implemented.

### Test
```bash
curl -X POST localhost:8000 \
  --data '{"jsonrpc":"2.0", "method": "eth_getStorageAt", "params": ["0xffffffffffffffffffffffffffffffffffffff04", "0x0", "latest"], "id": 1}' \
  --header 'Content-Type: application/json' 

# Result
{"jsonrpc":"2.0","id":1,"result":"0x00000000000000000000000000000000000000000000000000000000000004d2"}
```

## Expected result
[Not allow to call system contract address](https://github.com/axonweb3/axon/pull/1597/files#diff-7dedadc749f34a439efcf21029dbc46d5551c34bafd11e30faf0f6d3ee688650R54-R55)

ref: https://github.com/axonweb3/axon/issues/1561#issuecomment-1814374378
