### ISSUE TITLE
The `call` method in executor should handle system contracts as `exec` method does.

### ISSUE THREAD

**Issue by chaoticlonghair** [axonweb3/axon#1592]
#### Current status

- The `exec` method in executor do special operations for system contracts.

  https://github.com/axonweb3/axon/blob/264a67673334cdbf7e1021e5af71f21c95553fea/core/executor/src/lib.rs#L152-L153

- But `call` method doesn't.

  https://github.com/axonweb3/axon/blob/264a67673334cdbf7e1021e5af71f21c95553fea/core/executor/src/lib.rs#L65

#### Issues introduced by the above Design

When `call` system contracts —— for example, call `eth_estimateGas` —— it may lead to unexpected results.

Also, unexpected results may be occurred when replay system contracts (ref: [#1234](https://github.com/axonweb3/axon/pull/1234/files#diff-d0322ab6b3113598aad221e9d896f27b0a0d2376a5eddbce7323403164025821R203) tried).

#### Proposals

- Do same operations for both `exec` and `call`.

- Or, just reject system contracts directly in the `call` method.

**Comment by Flouse** [comment]
### confirmed solution
- just reject system contracts directly in the call method

**Comment by chaoticlonghair** [comment]
I found that #1597 will resolve this issue.

_p.s. This comment is created via [GitHub CLI](https://cli.github.com/ "Try it!")._
