### ISSUE TITLE
Get an custom error from `eth_getTransactionHash`

### ISSUE THREAD

**Issue by Keith-CY** [axonweb3/axon#375]
**What happened**:
![image](https://user-images.githubusercontent.com/7271329/169703107-7a85ae0b-2efd-42a7-81ee-1ec16cf3aec9.png)

Trying to get a transaction from the internal testing node with `0x8612c1833c6bc876ac1389b65831adb5cbb662734492dafb9906cc7f1a29d6be` which is listed in the genesis block, but get an error `Custom error: can not get receipt by hash 0x8612c1833c6bc876ac1389b65831adb5cbb662734492dafb9906cc7f1a29d6be`

**What you expected to happen**:
A valid transaction returned
![image](https://user-images.githubusercontent.com/7271329/169703244-2fd0e18a-db26-4c83-8bca-c79c83a7cebc.png)

Or `null` returned if the transaction is not found
![image](https://user-images.githubusercontent.com/7271329/169703252-e8023746-4325-4bf3-831d-1e92c8a27b3d.png)

**Comment by KaoImin** [comment]
The transactions in genesis do not have receipts.

**Comment by Keith-CY** [comment]
Ethereum's genesis block includes genesis_txns too but they are all not returned by RPC

```
{
	"jsonrpc": "2.0",
	"id": 1,
	"result": {
		"difficulty": "0x400000000",
		"extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
		"gasLimit": "0x1388",
		"gasUsed": "0x0",
		"hash": "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
		"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
		"miner": "0x0000000000000000000000000000000000000000",
		"mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"nonce": "0x0000000000000042",
		"number": "0x0",
		"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
		"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
		"size": "0x21c",
		"stateRoot": "0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544",
		"timestamp": "0x0",
		"totalDifficulty": "0x400000000",
		"transactions": [],
		"transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
		"uncles": []
	}
}
```

Is returning block with genesis_txns by design?

**Comment by KaoImin** [comment]
> Ethereum's genesis block includes genesis_txns too but they are all not returned by RPC
> 
> ```
> {
> 	"jsonrpc": "2.0",
> 	"id": 1,
> 	"result": {
> 		"difficulty": "0x400000000",
> 		"extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
> 		"gasLimit": "0x1388",
> 		"gasUsed": "0x0",
> 		"hash": "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
> 		"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
> 		"miner": "0x0000000000000000000000000000000000000000",
> 		"mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
> 		"nonce": "0x0000000000000042",
> 		"number": "0x0",
> 		"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
> 		"receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
> 		"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
> 		"size": "0x21c",
> 		"stateRoot": "0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544",
> 		"timestamp": "0x0",
> 		"totalDifficulty": "0x400000000",
> 		"transactions": [],
> 		"transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
> 		"uncles": []
> 	}
> }
> ```
> 
> Is returning block with genesis_txns by design?

This is controlled by [SHOW TRANSACTION DETAILS FLAG](https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_getblockbynumber).

**Comment by Keith-CY** [comment]
> > Ethereum's genesis block includes genesis_txns too but they are all not returned by RPC
> > ```
> > {
> > 	"jsonrpc": "2.0",
> > 	"id": 1,
> > 	"result": {
> > 		"difficulty": "0x400000000",
> > 		"extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
> > 		"gasLimit": "0x1388",
> > 		"gasUsed": "0x0",
> > 		"hash": "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
> > 		"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
> > 		"miner": "0x0000000000000000000000000000000000000000",
> > 		"mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
> > 		"nonce": "0x0000000000000042",
> > 		"number": "0x0",
> > 		"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
> > 		"receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
> > 		"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
> > 		"size": "0x21c",
> > 		"stateRoot": "0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544",
> > 		"timestamp": "0x0",
> > 		"totalDifficulty": "0x400000000",
> > 		"transactions": [],
> > 		"transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
> > 		"uncles": []
> > 	}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is returning block with genesis_txns by design?
> 
> This is controlled by [SHOW TRANSACTION DETAILS FLAG](https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_getblockbynumber).

It might be confused, the second parameter `show tx detail` is used to toggle the data in `block.transactions`, `tx hash list` will be returned if `show tx detail` is `false`, otherwise, `tx details list` will be returned.

**Comment by Keith-CY** [comment]
When I say `Ethereum's genesis block includes genesis_txns too but they are all not returned by RPC`
I mean there're many transactions in the genesis block
![image](https://user-images.githubusercontent.com/7271329/171544486-a0a5a52b-4885-422a-8f77-c41f3666558e.png)
but they are not listed in response of RPC
```
{
	"jsonrpc": "2.0",
	"id": 1,
	"result": {
		"difficulty": "0x400000000",
		"extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
		"gasLimit": "0x1388",
		"gasUsed": "0x0",
		"hash": "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
		"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
		"miner": "0x0000000000000000000000000000000000000000",
		"mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"nonce": "0x0000000000000042",
		"number": "0x0",
		"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
		"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
		"size": "0x21c",
		"stateRoot": "0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544",
		"timestamp": "0x0",
		"totalDifficulty": "0x400000000",
		"transactions": [],
		"transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
		"uncles": []
	}
}
```

**Comment by KaoImin** [comment]
I see
