### ISSUE TITLE
Meet error when sending transaction through 'ethers' library

### ISSUE THREAD

**Issue by ashuralyk** [axonweb3/axon#621]
**What happened**:
![image](https://user-images.githubusercontent.com/3871265/184572763-688ba0e6-f8bb-4050-ac21-5eb8ce70cd5f.png)
![image](https://user-images.githubusercontent.com/3871265/184572805-6b607f8a-0883-48e7-b046-9b908485aa94.png)
![image](https://user-images.githubusercontent.com/3871265/184572820-abed5cdf-b41c-4886-8eec-40f215a2fd2f.png)

通过 'ethers' 库发起的调用 eth_sendRawTransaction 接口返回错误信息，但这个错误信息并不是每次都会出现，比较有可能的发生规律是在上一笔交易上链后不久再发起下一笔交易，很容易出现该问题，过一段时间再试便没有问题

**What you expected to happen**:
交易成功上链

**How to reproduce it (as minimally and precisely as possible)**:
1. 下载 axon-bridge-ui 库 (https://github.com/nervosnetwork/axon-bridge-ui)
2. 多次发起 axon => ckb 方向上的跨链交易

**Anything else we need to know?**:

**Environment**:

- Mercury version or commit hash (`git log -1`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Flouse** [comment]
Outdated
