### ISSUE TITLE
Axon contract address generation issue

### ISSUE THREAD

**Issue by ashuralyk** [axonweb3/axon#674]
**What happened**:
In Javascript/Web3 case，we use transaction nonce as BigNumber type and so as we use this nonce to create contract address. Most of time it works fine wether the nonce is BigNumber type or normal type, but except the "nonce = 0" as I can find so far.

We can tell:

if the nonce = 0 is normal type:
contract address of administrator of Axon is **0xa13763691970d9373d4fab7cc323d7ba06fa9986** (which is used by current Axon implementation)

if the nonce = 0 is BigNumber type:
contract address of administrator of Axon is **0x037d28ae1969b75a4d19ced217bf9f4bc611b446** (which I think is the right way to generate contract address)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
the only difference I found is happened in "nonce = 0" case, but I can't tell other cases won't meet this kind of difference, it should be careful to deal.

**Environment**:

- Mercury version or commit hash (`git log -1`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Flouse** [comment]
confirmed with @ashuralyk , this is an outdated issue.
