### ISSUE TITLE
eth_senRawTransaction panics 

### ISSUE THREAD

**Issue by distributedstatemachine** [axonweb3/axon#767]
**What happened**:

We are trying to send transactions to our node using the `eth_sendRawTransaction` json rpc end point. When we try calling it via the command line / postman ,  we get the following error 

```
FetchError: request to http://34.204.204.212:8000/ failed, reason: socket hang up
```

Upon inspecting the logs , we need that the json rpc server is crashing  and causing the program to panic : https://gist.github.com/samtvlabs/c8b3134675c481080231bb329a3644b4

**What you expected to happen**:

The transaction should be successful and return a transaction hash.

**How to reproduce it (as minimally and precisely as possible)**:

* build a release version of the code master branch

```bash
cargo build release
```

* Start axon

```bash
target/release/axon -c devtools/chain/config.toml -g devtools/chain/genesis_single_node.json
```

* make this rpc call via postman or curl 

```bash
curl --location --request POST 'localhost:8000/' \
--header 'Content-Type: application/json' \
--data-raw '{
	"jsonrpc":"2.0",
	"method":"eth_sendRawTransaction",
	"params":["0xf9043f098502540be4008344f74d8080b9042c60806040526100163364010000000061001b810204565b61003d565b60068054600160a060020a031916600160a060020a0392909216919091179055565b6103e08061004c6000396000f3006080604052600436106100775763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416633ad06d1681146100c257806354fd4d50146100e85780635c60da1b1461010f5780636fde820214610140578063a9c45fcb14610155578063f1739cae14610179575b600061008161019a565b9050600160a060020a038116151561009857600080fd5b60405136600082376000803683855af43d82016040523d6000833e8080156100be573d83f35b3d83fd5b3480156100ce57600080fd5b506100e6600435600160a060020a03602435166101a9565b005b3480156100f457600080fd5b506100fd6101d3565b60408051918252519081900360200190f35b34801561011b57600080fd5b5061012461019a565b60408051600160a060020a039092168252519081900360200190f35b34801561014c57600080fd5b506101246101d9565b6100e6600480359060248035600160a060020a0316916044359182019101356101e8565b34801561018557600080fd5b506100e6600160a060020a0360043516610250565b600854600160a060020a031690565b6101b16101d9565b600160a060020a031633146101c557600080fd5b6101cf82826102d8565b5050565b60075490565b600654600160a060020a031690565b6101f06101d9565b600160a060020a0316331461020457600080fd5b61020e84846101a9565b30600160a060020a03163483836040518083838082843782019150509250505060006040518083038185875af192505050151561024a57600080fd5b50505050565b6102586101d9565b600160a060020a0316331461026c57600080fd5b600160a060020a038116151561028157600080fd5b7f5a3e66efaa1e445ebd894728a69d6959842ea1e97bd79b892797106e270efcd96102aa6101d9565b60408051600160a060020a03928316815291841660208301528051918290030190a16102d58161037d565b50565b600854600160a060020a03828116911614156102f357600080fd5b6102fc816103ac565b151561030757600080fd5b600754821161031557600080fd5b600782905560088054600160a060020a03831673ffffffffffffffffffffffffffffffffffffffff1990911681179091556040805184815290517f4289d6195cf3c2d2174adf98d0e19d4d2d08887995b99cb7b100e7ffe795820e9181900360200190a25050565b6006805473ffffffffffffffffffffffffffffffffffffffff1916600160a060020a0392909216919091179055565b6000903b11905600a165627a7a72305820367593e912fa4bfc7d8aa365738abd53d47d9e399bca3a9e7859539be7ec86580029808080"],
	"id":1
}'
```

**Anything else we need to know?**:

**Environment**:

- Mercury version or commit hash (`git log -1`): 162e17975db7273871fa90b28349e977453d2f7c
- OS (e.g: `cat /etc/os-release`):
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
- Kernel (e.g. `uname -a`): 
```
Linux ip-172-31-70-167 5.15.0-1019-aws #23-Ubuntu SMP Wed Aug 17 18:33:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
- Others:

**Comment by Hanssen0** [comment]
Hi!

Thank you for your feedback. The crashing of `Axon` is unexpected and we are fixing this bug, see #768.

Looks like your transaction is for creating an account (deploying a contract I guess). However, the transaction is incomplete since it hasn't been signed. Sign the transaction if you are planning to send it successfully.

**Comment by distributedstatemachine** [comment]
Thanks for your quick response!! .

I believe this transaction has been signed . Please advise if wrong , but I copied it by logging the signature from the signed transaction from the deployment script.

```javascript
    const tx = new Transaction(rawTx, { common: customCommon })
    // const txEthers = new ethers
    tx.sign(privateKey)
    const serializedTx = tx.serialize()
    console.log('serializedTx', `0x${serializedTx.toString('hex')}`) <=== Copied this
```

**Comment by Hanssen0** [comment]
> Thanks for your quick response!! .
> 
> I believe this transaction has been signed . Please advise if wrong , but I copied it by logging the signature from the signed transaction from the deployment script.
> 
> ```js
>     const tx = new Transaction(rawTx, { common: customCommon })
>     // const txEthers = new ethers
>     tx.sign(privateKey)
>     const serializedTx = tx.serialize()
>     console.log('serializedTx', `0x${serializedTx.toString('hex')}`) <=== Copied this
> ```

1. The `r`, `s` and `v` fields of your transaction are empty, so it's not signed.
2. Please see [@ethereumjs/tx Transaction.sign](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/docs/classes/Transaction.md#sign).

> Note that the signed tx is returned as a new object, use as follows:
> ```js
> const signedTx = tx.sign(privateKey)
> ```
